/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["selector", "[data-theme='dark']"],
  theme: {
    extend: {
      colors: {
        ink: {
          950: "#0a0e17",
          900: "#0f1420",
          850: "#141b2b",
          800: "#1a2336",
          700: "#243049",
          600: "#33415f",
        },
        brim: {
          400: "#5eead4",
          500: "#2dd4bf",
          600: "#14b8a6",
        },
        accent: "#7c83ff",
        // Stitch design system colors
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary-container": "#6f7ae5",
        "tertiary-container": "#000767",
        "outline": "#76777d",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed-dim": "#bdc2ff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#316bf3",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "secondary": "#0051d5",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#2f3aa3",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed": "#131b2e",
        "on-surface-variant": "#45464d",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-tint": "#565e74",
        "tertiary-fixed": "#e0e0ff",
        "inverse-primary": "#bec6e0",
        "surface-dim": "#d8dadc",
        "primary": "#000000",
        "background": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#000767",
        "on-secondary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "sm": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "row-height-standard": "48px",
        "base": "4px",
        "row-height-dense": "32px",
        "gutter": "16px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "data-mono": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        display: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"]
      },
    },
  },
  plugins: [],
};

